#Mutant Creeper spawn weight.
#Range: 0 ~ 100
mutant_creeper_spawn_weight = 0
#Mutant Enderman spawn weight.
#Range: 0 ~ 100
mutant_enderman_spawn_weight = 0
#Mutant Skeleton spawn weight.
#Range: 0 ~ 100
mutant_skeleton_spawn_weight = 0
#Mutant Zombie spawn weight.
#Range: 0 ~ 100
mutant_zombie_spawn_weight = 3

